name: Build and Push Docker Images for Changed Projects

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed projects
        id: changes
        run: |
          echo "Changed folders:"
          changed_folders=$(git diff --name-only HEAD^ HEAD | grep / | cut -d/ -f1 | sort -u | tr '\n' ' ')
          echo "Detected: $changed_folders"
          echo "changed=$changed_folders" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push WebAPI image
        if: contains(steps.changes.outputs.changed, 'webapi')
        uses: docker/build-push-action@v4
        with:
          context: ./webapi
          file: ./webapi/Dockerfile.prod
          push: true
          tags: fadisami/webapiapp:prod

      - name: Build and Push RazorApp image
        if: contains(steps.changes.outputs.changed, 'razorapp')
        uses: docker/build-push-action@v4
        with:
          context: ./razorapp
          file: ./razorapp/Dockerfile.prod
          push: true
          tags: fadisami/razorapp:prod
