steps:
  - name: Checkout repository
    uses: actions/checkout@v3
    with:
      fetch-depth: 0 # fetch full history for diff

  - name: Get list of changed files
    id: changed-files
    run: |
      # If this is the first commit on the branch (no before SHA), diff against main
      if [[ "${{ github.event.before }}" == "0000000000000000000000000000000000000000" ]]; then
        git fetch origin main
        git diff --name-only origin/main HEAD > files.txt
      else
        git diff --name-only ${{ github.event.before }} ${{ github.sha }} > files.txt
      fi
      echo "Changed files:"
      cat files.txt
      # Set output for use in other jobs (e.g. join into a space-separated string)
      echo "files=$(paste -sd' ' files.txt)" >> $GITHUB_OUTPUT

  - name: Build WebAPI if it changed
    if: ${{ contains(steps.changed-files.outputs.files, 'webapi/') }}
    run: |
      echo "webapi/ changed – running WebAPI build..."

  - name: Build RazorApp if it changed
    if: ${{ contains(steps.changed-files.outputs.files, 'razorapp/') }}
    run: |
      echo "razorapp/ changed – running RazorApp build..."
