name: Build and Push Docker Images for Changed Projectss

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Detect changed projects
        id: changes
        run: |
          echo "Changed folders:"
          # Get list of changed folders in the push commit(s)
          echo "::set-output name=changed::$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep / | cut -d/ -f1 | sort -u | tr '\n' ' ')"
      
      - name: Show changed projects
        run: echo "Changed projects: ${{ steps.changes.outputs.changed }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD}}

      - name: Build and Push WebAPI image
        if: contains(steps.changes.outputs.changed, 'webapi')
        uses: docker/build-push-action@v4
        with:
          context: ./webapi
          file: ./webapi/Dockerfile.prod
          push: true
          tags: fadisami/webapiapp:prod

      - name: Build and Push RazorApp image
        if: contains(steps.changes.outputs.changed, 'razorapp')
        uses: docker/build-push-action@v4
        with:
          context: ./razorapp
          file: ./razorapp/Dockerfile.prod
          push: true
          tags: fadisami/razorapp:prod
